language: scala

scala:
  - 2.12.10
  - 2.11.12
jdk:
  - openjdk8

notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s

script:
  - sbt clean coverage test it:test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
